2024-12-05 22:47:23 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:27 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:30 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:34 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:37 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:40 - ERROR - Ошибка при отправке события: HTTPSConnectionPool(host='api.appmetrica.yandex.ru', port=443): Max retries exceeded with url: /logs/v1/import/events?post_api_key=09c5118e-49a4-4703-af8b-460157a13cfb&application_id=4649854&appmetrica_device_id=14766913885733900580&event_name=DeviceAttendanceStudent&event_timestamp=1733427984&event_json=%7B%22device_id%22%3A+1%2C+%22student_id%22%3A+1%2C+%22schedule_id%22%3A+11%7D&session_type=foreground (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef314598b0>: Failed to establish a new connection: [Errno 60] Operation timed out'))


2024-12-05 22:47:41 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:45 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:48 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:52 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:47:55 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:09 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:13 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:16 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:19 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:23 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:49:26 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:50:36 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:50:40 - ERROR - Лицо не обнаружено на изображении
NoneType: None


2024-12-05 22:50:43 - ERROR - Лицо не обнаружено на изображении
NoneType: None


