2025-04-06 23:04:34 - ERROR - Необработанная ошибка: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/.venv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/.venv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/.venv/lib/python3.8/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/chronos_386/PycharmProjects/FaceRecognizerServer/source_code/resources/admin_subject_actions_res.py", line 33, in put
    subject_id: int = int(request.form.get('subject_id'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


